In [4]:
import numpy as np

Создайте массив из 20 случайных чисел и найдите их сумму с накоплением.

Функция numpy.cumsum возвращает массив с накопленной суммой элементов по заданному измерению

In [10]:
asdrandom = np.random.randint(1,100, size = 20)
print(asdrandom)

cumsum = np.cumsum(asdrandom)
cumsum

[82 34 61 10 53 91 72 66 22 87 51 93 41 75 92 57 38  1 69 51]


array([  82,  116,  177,  187,  240,  331,  403,  469,  491,  578,  629,
        722,  763,  838,  930,  987, 1025, 1026, 1095, 1146])

Создайте массив из 10 элементов со значениями от 0 до 9, изменённый в форму 2×5.

In [13]:
a = np.arange(10)
b = a.reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Создайте массив из чисел от 0 до 100 с шагом 5

In [17]:
a = np.arange(0,100,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

Найдите размах (max - min) и межквартильный размах массива.

Сокращение "ptp" расшифровывается как "от пика до пика". Эта функция используется для возврата диапазона значений вдоль оси.

In [34]:
a = np.array([5,12,23,34,45,56,67,78,89,97,1,34,63,82,84,223,86,4,3])
b = np.ptp(a)
b

np.int64(222)

Создайте матрицу 4×4 и найдите её собственные значения и векторы.

numpy.linalg.eig() вычисляет собственные значения и правые собственные векторы квадратной матрицы.

In [62]:
my_matrix = np.random.randint(1,100, size = (4,4))
my_matrix

a,b = np.linalg.eig(my_matrix)
print("значения:")
print(a)

print("Векторы:")
print(b)

значения:
[183.54155078+0.j -62.79074124+0.j  -1.83042859+0.j  72.07961904+0.j]
Векторы:
[[-0.26653313+0.j -0.31556358+0.j  0.63294286+0.j  0.11888674+0.j]
 [-0.42852134+0.j  0.80543212+0.j  0.34798046+0.j -0.44939774+0.j]
 [-0.60692952+0.j -0.44234421+0.j -0.65832459+0.j -0.43173679+0.j]
 [-0.61397566+0.j  0.23670727+0.j -0.21190013+0.j  0.77298833+0.j]]


Извлеките элементы массива [1, 2, 3, 4, 5, 6], стоящие на нечётных позициях.

In [63]:
a=np.array([1,2,3,4,5,6])
b = a[0::2]
b

array([1, 3, 5])

Создайте массив 6×6 и замените элементы главной диагонали на 0.

Функция numpy.diag_indices(n, ndim=2) возвращает кортеж массивов индексов для доступа к главной диагонали квадратного или многомерного массива.

In [69]:
a = np.arange(36)
b = a.reshape(6,6)
c = np.diag_indices(6)
b[c] = 0
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  0,  8,  9, 10, 11],
       [12, 13,  0, 15, 16, 17],
       [18, 19, 20,  0, 22, 23],
       [24, 25, 26, 27,  0, 29],
       [30, 31, 32, 33, 34,  0]])

Объедините два массива, чередуя их элементы: [1, 3, 5] и [2, 4, 6] → [1, 2, 3, 4, 5, 6].

In [71]:
a = np.array([1,3,5])
b = np.array([2,4,6])

c = np.column_stack((a,b)).flatten()
c

array([1, 2, 3, 4, 5, 6])

Примените функцию np.select для категоризации массива по условиям.


Реализуйте свёртку (convolution) двух одномерных массивов.



2.1
Вычислить значения на интервале [0,1] с шагом 0.01 с точностью 0.01 для следующих функций и вывести на экран только положительные результаты
12)F(x)=x2-six2x

3.1

3.2